### Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.

In [7]:
import pandas as pd
data=pd.Series([10,20,30,40,50,60])
print(data)
print(type(data))

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64
<class 'pandas.core.series.Series'>


In [8]:
data_float=pd.Series([10.5,20.5,12.50,30.5,100.6,5,10])
print(data_float)
print(type(data_float))

0     10.5
1     20.5
2     12.5
3     30.5
4    100.6
5      5.0
6     10.0
dtype: float64
<class 'pandas.core.series.Series'>


In [9]:
test=pd.Series(['Hitesh',30,10.100,'Ralegaon'])
print(test)
print(type(test))

0      Hitesh
1          30
2        10.1
3    Ralegaon
dtype: object
<class 'pandas.core.series.Series'>


### Write a Pandas program to convert a Pandas module Series to Python list and it’s type.

In [11]:
number=pd.Series([10,22,33,40,45,55])
print(number)
print(type(number))
print()
print("Number after changing the dattype into Python LIST")
print(number.tolist())
print(type(number.tolist()))
print()


0    10
1    22
2    33
3    40
4    45
5    55
dtype: int64
<class 'pandas.core.series.Series'>

Number after changing the dattype into Python LIST
[10, 22, 33, 40, 45, 55]
<class 'list'>


### Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [18]:
data=pd.Series([10,20,30,35,40])
data1=pd.Series([20,75,12,25,50])
print()
print("Performing Addition Operation")
result=data+data1
print(result)
print()
print("Performing Subtraction Operation")
result1=data-data1
print(result1)
print()
print("Performing Multiplication Operation")
result2=data*data1
print(result2)
print()
print("Performing Division Operation")
result3=data/data1
print(result3)


Performing Addition Operation
0    30
1    95
2    42
3    60
4    90
dtype: int64

Performing Subtraction Operation
0   -10
1   -55
2    18
3    10
4   -10
dtype: int64

Performing Multiplication Operation
0     200
1    1500
2     360
3     875
4    2000
dtype: int64

Performing Division Operation
0    0.500000
1    0.266667
2    2.500000
3    1.400000
4    0.800000
dtype: float64


### Write a Pandas program to compare the elements of the two Pandas Series.

In [19]:
data=pd.Series([10,20,30,35,40])
data1=pd.Series([20,75,12,25,50])
print()

print("Comparing series is equal or not")
result=data==data1
print(result)
print()
print("Comparing data > data1")
result1=data>data1
print(result1)
print()
print("Comparing data < data1")
result1=data<data1
print(result1)




Comparing series is equal or not
0    False
1    False
2    False
3    False
4    False
dtype: bool

Comparing data > data1
0    False
1    False
2     True
3     True
4    False
dtype: bool

Comparing data < data1
0     True
1     True
2    False
3    False
4     True
dtype: bool


### Write a Pandas program to convert a dictionary to a Pandas series.

In [22]:
data={'name':['Hitesh','Sonal','Sannidhya','Pranay'],
      'Age':[31,34,5,16],
      'Education':['B.E','MBA','KG','High School']}
print(data)
print(type(data))
print()
print("Converting the dictionary into Seires")
print()
result=pd.Series(data)
print(result)
print(type(result))


{'name': ['Hitesh', 'Sonal', 'Sannidhya', 'Pranay'], 'Age': [31, 34, 5, 16], 'Education': ['B.E', 'MBA', 'KG', 'High School']}
<class 'dict'>

Converting the dictionary into Seires

name         [Hitesh, Sonal, Sannidhya, Pranay]
Age                             [31, 34, 5, 16]
Education           [B.E, MBA, KG, High School]
dtype: object
<class 'pandas.core.series.Series'>


### Write a Pandas program to convert a NumPy array to a Pandas series.

In [24]:
import numpy as np
number=np.array([10,20,30,40,50])
print(number)
print(type(number))
print()

result=pd.Series(number)
print(result)
print(type(result))

[10 20 30 40 50]
<class 'numpy.ndarray'>

0    10
1    20
2    30
3    40
4    50
dtype: int32
<class 'pandas.core.series.Series'>


### Write a Pandas program to change the data type of given a column or a Series.

In [31]:
name=pd.Series(['10','230','40','550','12.50','50','20'])
print(name)
print(type(name))
print()
print("Changing the type of Series")
print()
result=pd.to_numeric(name, errors='coerce')
print(result)
print(type(result))
print()

0       10
1      230
2       40
3      550
4    12.50
5       50
6       20
dtype: object
<class 'pandas.core.series.Series'>

Changing the type of Series

0     10.0
1    230.0
2     40.0
3    550.0
4     12.5
5     50.0
6     20.0
dtype: float64
<class 'pandas.core.series.Series'>



### Write a Pandas program to convert the first column of a DataFrame as a Series.

In [43]:
data={'name':['Hitesh','Sonal','Sannidhya','Pranay'],
      'Age':[31,34,5,16],
      'Education':['B.E','MBA','KG','High School']}
result=pd.DataFrame(data=data)
print(result)
print(type(result))
print()
print("Fetching first column from DataFrame")
print()
first_column=result.iloc[:,0]
print(first_column)
print(type(first_column))
print()


        name  Age    Education
0     Hitesh   31          B.E
1      Sonal   34          MBA
2  Sannidhya    5           KG
3     Pranay   16  High School
<class 'pandas.core.frame.DataFrame'>

Fetching first column from DataFrame

0       Hitesh
1        Sonal
2    Sannidhya
3       Pranay
Name: name, dtype: object
<class 'pandas.core.series.Series'>



### Write a Pandas program to convert a given Series to an array.

In [46]:
import numpy as np
number=pd.Series([100,200,300,400,500])
print(number)
print(type(number))
print()
print("Converting the python Series into array")
print()
result=np.array(number.tolist())
print(result)
print(type(result))

0    100
1    200
2    300
3    400
4    500
dtype: int64
<class 'pandas.core.series.Series'>

Converting the python Series into array

[100 200 300 400 500]
<class 'numpy.ndarray'>


### Write a Pandas program to convert Series of lists to one Series.

In [51]:
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']])

print(s)
print()
print("Merge all series into one single series")
print()
result=s.apply(pd.Series).stack()
print(result)

0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

Merge all series into one single series

0  0       Red
   1     Green
   2     White
1  0       Red
   1     Black
2  0    Yellow
dtype: object


In [60]:
name=pd.Series([['Hitesh','Ganesh','Suresh'],
               ['Sonal','Krunal','Sannu'],
               ['Pratik','Raju','Soyendra']])
print(name)
print(type(name))
print("Merge all series into one single series")
print()
result=name.apply(pd.Series).stack()
print()
print(result.sort_values(ascending=False))
print()
print("Adding some fdata into existing Series")
final_result=result.append(pd.Series(['Prajwal','Vandana']))
print(final_result)

0    [Hitesh, Ganesh, Suresh]
1      [Sonal, Krunal, Sannu]
2    [Pratik, Raju, Soyendra]
dtype: object
<class 'pandas.core.series.Series'>
Merge all series into one single series


0  2      Suresh
2  2    Soyendra
1  0       Sonal
   2       Sannu
2  1        Raju
   0      Pratik
1  1      Krunal
0  0      Hitesh
   1      Ganesh
dtype: object

Adding some fdata into existing Series
(0, 0)      Hitesh
(0, 1)      Ganesh
(0, 2)      Suresh
(1, 0)       Sonal
(1, 1)      Krunal
(1, 2)       Sannu
(2, 0)      Pratik
(2, 1)        Raju
(2, 2)    Soyendra
0          Prajwal
1          Vandana
dtype: object


### Write a Pandas program to create the mean and standard deviation of the data of a given Series.

In [64]:
number=[10,25,30,40,50,75]
print(type(number))
print()
print("Convert it into Series")
print()
result=pd.Series(number)
print(result)
print(type(result))
print()
print("Finding the mean of given Series")
print()
mean=result.mean()
print(mean)
print()
print("Finding the STD of given Series")
print()
std_dev=result.std()
print(std_dev)



<class 'list'>

Convert it into Series

0    10
1    25
2    30
3    40
4    50
5    75
dtype: int64
<class 'pandas.core.series.Series'>

Finding the mean of given Series

38.333333333333336

Finding the STD of given Series

22.50925735484551


### Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.

In [70]:
import numpy as np
from collections import Counter
data=np.random.randint(10,50,20)
print(data)
print()
print("\nMinimum, 25th percentile, median, 75th, and maximum of a given series:")
print()
result=np.percentile(data,q=[0,25,50,75,100])
print(result)
print()
count_num=Counter(data)
print(count_num)

[16 23 30 45 37 35 19 29 49 28 41 29 37 18 38 35 40 14 48 20]


Minimum, 25th percentile, median, 75th, and maximum of a given series:

[14.   22.25 32.5  38.5  49.  ]

Counter({37: 2, 35: 2, 29: 2, 16: 1, 23: 1, 30: 1, 45: 1, 19: 1, 49: 1, 28: 1, 41: 1, 18: 1, 38: 1, 40: 1, 14: 1, 48: 1, 20: 1})


### Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.

In [72]:
data=np.random.randint(10,50,20)
print(data)
print()
print()
result=np.where(data%5==0)
print(result)

[45 30 24 43 45 36 39 23 37 18 42 12 32 42 36 33 47 27 14 30]


(array([ 0,  1,  4, 19], dtype=int64),)
